name : deploy to firebase
on : 
  push :
    branches:
      - main

jobs:
  deploy:
    name : deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          docker-compose -f ./docker/docker-compose.yml run --rm firebase-tools
